FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /app

COPY dotnet-lib/ ./
COPY examples/Program.cs ./

RUN dotnet build
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/runtime:6.0
WORKDIR /app
COPY --from=build /app/out .

CMD ["dotnet", "DistributedLogging.dll"]
