FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY dashboard/ ./dashboard/
COPY python-lib/ ./python-lib/

EXPOSE 5000

CMD ["python", "dashboard/app.py"]
