apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: storage-node
  namespace: log-processing
spec:
  serviceName: storage-headless
  replicas: 3
  selector:
    matchLabels:
      app: storage-node
      component: storage
  template:
    metadata:
      labels:
        app: storage-node
        component: storage
    spec:
      containers:
      - name: storage
        image: log-processing-storage:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9090
          name: storage-port
        env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: STORAGE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: STORAGE_PASSWORD
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 9090
          initialDelaySeconds: 20
          periodSeconds: 5
        volumeMounts:
        - name: storage-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: storage-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
