apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: logcollectors.logs.platform.io
spec:
  group: logs.platform.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                sources:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      endpoint:
                        type: string
                targetProcessors:
                  type: array
                  items:
                    type: string
            status:
              type: object
              properties:
                state:
                  type: string
                activeConnections:
                  type: integer
  scope: Namespaced
  names:
    plural: logcollectors
    singular: logcollector
    kind: LogCollector
    shortNames:
      - lc
